# Site settings
title: An artistic blog of Phuong Tra (ptra31)
email: 
description: "The Magic of Arts."
baseurl: ""
url: "http://ptra31.github.io"
twitter_username:
github_username:  ptra31

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
